version: 0.0
os: linux

files:
  - source: /
    # CRITICAL FIX: Use the permanent project directory
    destination: /home/ubuntu/MyPortfolio/ 
    overwrite: true # Ensures old files are correctly replaced

hooks:
  ApplicationStop:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
      
  ApplicationStart:
    # This hook will now run the script in the context of the copied files
    - location: scripts/deploy.sh
      timeout: 300
      runas: root