version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/MyPortfolio/ # <--- CHANGE THIS
    overwrite: true # <--- CRITICAL: Add this to allow updating existing files

hooks:
  ApplicationStop:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root