version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/MyPortfolio
    overwrite: true

hooks:

  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
